Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('newsfeed/', include('newsfeed.urls', namespace='newsfeed')),

    path('theboss/', admin.site.urls),
    path('', include('app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('otp-verify/', views.otp_verify, name='otp_verify'),
    path('newsfeed/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    # path('create-group/', views.create_group_view, name='create_group'),
    # path('join-group/', views.join_group_view, name='join_group'),
    path('chat/', views.chat_view, name='joinChat'),
    path('profile/<str:username>', views.profile_view, name='profile'),
    path('chat/<username>', views.get_or_create_chat, name='start-chat'),
    path('chat/room/<chatroom_name>', views.chat_view, name="chatroom"),
    path('upload-img/', views.upload_img, name='profile-img'),
]

Project/app/templates/chat/chat.html
{% extends "base.html" %}
{% block chatbox %}

<div ws-receive></div>
<div class="max-w-md mx-auto mt-10 bg-white shadow-lg rounded-xl flex flex-col h-[500px]">
    
    <div class="bg-blue-600 text-white px-4 py-3 rounded-t-xl flex justify-between items-center">
    {% if chat_group.is_private %}
      {% if other_user %}
      <div id="online-icon"></div>
      {% for p in profile %}
      <div class="flex flex-col items-center mx-auto">
        <img 
        src="{{  p.image.url }}" 
        alt="Profile Image" 
        class="w-10 h-10 mr-3 -mt-1 rounded-full object-cover border-4 border-blue-500 shadow-lg"
      />
      {% endfor %}
      {% for otherUser in other_user %}
      <div class="text-lg font-semibold  ml-20 -mt-9">@{{ otherUser.username }}</div>
      </div>
      {% endfor %}
{% endif %}
      {% else %}
      <h2 class="text-lg font-semibold">{{ chat_room_name }}</h2>
      <div id="online-icon"></div>
      <span id="online-count" class="text-sm font-light"></span>
      {% endif %}
    </div>
  
    <!-- Chat Messages -->
    <div id="chat-messages" class="flex-1 overflow-y-auto p-4 space-y-2 bg-gray-50">
      
      {% for message in chat_messages %}
      {% include 'chat/chat_message.html'%}
      {% endfor %}
    </div>
  
    
    <form  class="px-4 py-3 border-t border-gray-200 flex gap-2"
    hx-ext="ws"
    ws-connect="/ws/chat/{{ chat_room_name }}/"
    ws-send
    _="on htmx:wsAfterSend reset() me">
       {% csrf_token %}
       <input 
        type="text" 
        name="message" 
        placeholder="Type your message..." 
        class="flex-1 px-4 py-2 border rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500"
      />
       <button 
        type="submit" 
        class="bg-blue-600 text-white px-4 py-2 rounded-full hover:bg-blue-700 transition"
      >
        Send
      </button>
    </form>
  </div>
  {% endblock %}

  {% block script %}
  <script>
  
      function scrollToBottom() {
        const chatMessages = document.getElementById("chat-messages");
        if (chatMessages) {
          chatMessages.scrollTop = chatMessages.scrollHeight;
        }
      }
  
      scrollToBottom();
    
      document.addEventListener('htmx:oobAfterSwap', function(evt) {
        if (evt.detail.target.id === "chat-messages") {
          scrollToBottom();
        }
        
      });
  
  </script>
  
  {% endblock %}

Project/app/templates/chat/chat_message.html
{% load static %}

{% if message.user == user %}
      <div class="flex justify-end">
        <div class="bg-gray-200 text-gray-800 px-4 py-2 rounded-lg max-w-xs">
         {{ message.decrypt_message}}
        </div>
      </div>
{% else %}
      <div class="flex justify-start">
    {% if sender_profile %}
        {% if sender_profile.user == message.user %}
          <a href="{% url 'app:profile' message.user.username %}">
          <img src="{{ sender_profile.image.url }}" alt="User" class="w-10 h-10 rounded-full" />
          </a>
        {% endif %}
    {% else %}
    {% for p in profile %}
        {% if p.user == message.user %}

        <a href="{% url 'app:profile' message.user.username %}">

        <a href="{% url 'profile' message.user.username %}">
          {% if p.image %}

        <img src="{{ p.image.url }}" alt="User" class="w-10 h-10 rounded-full" />
          {% else %}
          <img src="{% static 'images/default_img.png' %}" alt="User" class="w-10 h-10 rounded-full" />
          {% endif %}
        </a>
        {% endif %}
    {% endfor %} 
  {% endif %}   

        <div class="bg-blue-500 text-white px-4 py-2 rounded-lg max-w-xs">
          {{ message.decrypt_message }}
        </div>
      </div>
      <div class="text-sm font-light py-0 ml-0"> 
        <span class="text-black-400">@{{ message.user.username }}</span>
    </div>

{% endif %}

Project/app/templates/chat/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% load static %}
{% block profile %}
<main class="flex-grow flex items-center justify-center">
    <div class="text-center">
      {% if profile.image %}
      <img 
        src="{{ profile.image.url }}" 
        alt="Profile Image" 
        class="w-48 h-48 rounded-full object-cover border-4 border-blue-500 shadow-lg"
      />
      <h2 class="mt-4 text-xl font-semibold text-gray-800">{{ username }}</h2>
      {% else %}
        <img 
        src="{% static 'images/default_img.png' %}" 
        alt="Profile Image" 
        class="w-48 h-48 rounded-full object-cover border-4 border-blue-500 shadow-lg"
      />
      <h2 class="mt-4 text-xl font-semibold text-gray-800">{{ username }}</h2>
      <a href="{% url 'app:profile-img' %}" class="mt-4 inline-block text-xl font-semibold text-white bg-blue-600 px-4 py-2 rounded hover:bg-blue-700 transition">
        Upload image</a>
      {% endif %}
      
      {% if request.user.username != username %}
      <a href="{% url 'app:start-chat' username %}" class="mt-4 inline-block text-xl font-semibold text-white bg-blue-600 px-4 py-2 rounded hover:bg-blue-700 transition">
      Chat with me
      </a>
      {% endif %}
      
    </div>
  </main>
 {% endblock %}

Project/app/templates/chat/upload.html
{% extends "base.html" %}
{% block image_upload %}
<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <form method="post" enctype="multipart/form-data" class="w-full max-w-md bg-white p-6 rounded-xl shadow-md space-y-4">
    {% csrf_token %}

    <div>
      <label for="image" class="block text-sm font-medium text-gray-700">Upload Profile Image</label>
      <input type="file" name="image" id="image" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" required>
    </div>

    <div>
      <button type="submit" class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition">
        Upload
      </button>
    </div>
  </form>
</div>
{% endblock %}